# Generated by Django 4.0.3 on 2022-03-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=0, max_length=255)),
                ('lat', models.CharField(default=0, max_length=255)),
                ('long', models.CharField(default=0, max_length=255)),
            ],
        ),
    ]
