# Generated by Django 4.0.3 on 2022-03-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapperapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coords',
            name='city',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='coords',
            name='country',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='coords',
            name='state',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
