# Generated by Django 4.0.3 on 2022-03-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapperapp', '0002_coords_city_coords_country_coords_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='coords',
            name='access_token',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
