# Generated by Django 4.0.3 on 2022-03-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapperapp', '0003_coords_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='coords',
            name='ip_address',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
