# Generated by Django 4.0.3 on 2022-03-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapperapp', '0004_coords_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='registeredWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=0, max_length=255)),
                ('website', models.CharField(default=0, max_length=255)),
            ],
        ),
    ]
