# Generated by Django 4.0.3 on 2022-03-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapperapp', '0005_registeredwebsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='coords',
            name='website',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
