# Generated by Django 4.0.3 on 2022-03-30 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapperapp', '0006_coords_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coords',
            old_name='website',
            new_name='website_id',
        ),
    ]
